# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0001_initial"),
        ("clinics", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "current_queue_number",
                    models.PositiveIntegerField(
                        default=0, verbose_name="شماره صف فعلی"
                    ),
                ),
                (
                    "total_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل نوبت\u200cها"
                    ),
                ),
                (
                    "completed_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای انجام شده"
                    ),
                ),
                (
                    "remaining_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای باقیمانده"
                    ),
                ),
                (
                    "average_visit_duration",
                    models.PositiveIntegerField(
                        default=0, verbose_name="میانگین زمان ویزیت (دقیقه)"
                    ),
                ),
                (
                    "estimated_wait_time",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تخمین زمان انتظار (دقیقه)"
                    ),
                ),
                (
                    "is_doctor_available",
                    models.BooleanField(default=True, verbose_name="پزشک حاضر"),
                ),
                (
                    "doctor_break_until",
                    models.TimeField(blank=True, null=True, verbose_name="استراحت تا"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع کار"
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_statuses",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "current_appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_queue_status",
                        to="appointments.appointment",
                        verbose_name="نوبت فعلی",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_statuses",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "وضعیت صف",
                "verbose_name_plural": "وضعیت صف\u200cها",
                "db_table": "queue_status",
                "ordering": ["-date"],
                "unique_together": {("doctor", "clinic", "date")},
            },
        ),
        migrations.CreateModel(
            name="QueueLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("call_next", "فراخوانی نفر بعدی"),
                            ("complete", "پایان ویزیت"),
                            ("skip", "رد شدن"),
                            ("recall", "فراخوانی مجدد"),
                            ("break_start", "شروع استراحت"),
                            ("break_end", "پایان استراحت"),
                            ("day_start", "شروع کار"),
                            ("day_end", "پایان کار"),
                        ],
                        max_length=20,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments.appointment",
                        verbose_name="نوبت",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام توسط",
                    ),
                ),
                (
                    "queue_status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="queue.queuestatus",
                        verbose_name="صف",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ صف",
                "verbose_name_plural": "لاگ\u200cهای صف",
                "db_table": "queue_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QueueAnnouncement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "is_global",
                    models.BooleanField(
                        default=False, verbose_name="نمایش در همه صف\u200cها"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "priority",
                    models.PositiveIntegerField(default=0, verbose_name="اولویت"),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ شروع"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ پایان"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_announcements",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_announcements",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان صف",
                "verbose_name_plural": "اعلان\u200cهای صف",
                "db_table": "queue_announcement",
                "ordering": ["-priority", "-created_at"],
            },
        ),
    ]
