# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره موبایل باید با 09 شروع شود و 11 رقم باشد",
                                regex="^09\\d{9}$",
                            )
                        ],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="نام")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="نام خانوادگی"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmin", "مدیر کل"),
                            ("doctor", "پزشک"),
                            ("secretary", "منشی"),
                            ("staff", "کارمند"),
                            ("patient", "بیمار"),
                        ],
                        default="patient",
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="کد ملی باید 10 رقم باشد", regex="^\\d{10}$"
                            )
                        ],
                        verbose_name="کد ملی",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ تولد"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "مرد"), ("female", "زن"), ("other", "سایر")],
                        max_length=10,
                        null=True,
                        verbose_name="جنسیت",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="نشانی"),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False, verbose_name="دسترسی پنل مدیریت"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="تأیید شده"),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="تاریخ عضویت"
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین ورود"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
                "db_table": "accounts_user",
                "ordering": ["-date_joined"],
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=11, verbose_name="شماره موبایل")),
                ("code", models.CharField(max_length=6, verbose_name="کد تأیید")),
                (
                    "code_type",
                    models.CharField(
                        choices=[
                            ("register", "ثبت\u200cنام"),
                            ("login", "ورود"),
                            ("password_reset", "بازیابی رمز"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="نوع کد",
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="استفاده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاریخ انقضا")),
            ],
            options={
                "verbose_name": "کد تأیید",
                "verbose_name_plural": "کدهای تأیید",
                "db_table": "accounts_verification_code",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="کلید نشست"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "device_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="نوع دستگاه"
                    ),
                ),
                (
                    "browser",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="مرورگر"
                    ),
                ),
                (
                    "os",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="سیستم عامل"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="موقعیت"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین فعالیت"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشست کاربر",
                "verbose_name_plural": "نشست\u200cهای کاربران",
                "db_table": "accounts_user_session",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "ایجاد"),
                            ("update", "ویرایش"),
                            ("delete", "حذف"),
                            ("login", "ورود"),
                            ("logout", "خروج"),
                            ("password_change", "تغییر رمز"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="عملیات",
                    ),
                ),
                (
                    "model_name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="نام مدل"
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه شیء"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="نمایش شیء"
                    ),
                ),
                (
                    "changes",
                    models.JSONField(blank=True, null=True, verbose_name="تغییرات"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "لاگ تغییرات",
                "verbose_name_plural": "لاگ\u200cهای تغییرات",
                "db_table": "accounts_audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="accounts_au_user_id_470480_idx",
                    ),
                    models.Index(
                        fields=["action"], name="accounts_au_action_0c03fe_idx"
                    ),
                    models.Index(
                        fields=["model_name", "object_id"],
                        name="accounts_au_model_n_46557c_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["phone"], name="accounts_us_phone_f54457_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["national_code"], name="accounts_us_nationa_8afd66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active"], name="accounts_us_is_acti_a5841d_idx"
            ),
        ),
    ]
