# Generated by Django 4.2.28 on 2026-02-04 09:23

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام مرکز")),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="شماره تلفن باید 11 رقم باشد", regex="^\\d{11}$"
                            )
                        ],
                        verbose_name="تلفن",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="موبایل"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="ایمیل"
                    ),
                ),
                ("province", models.CharField(max_length=50, verbose_name="استان")),
                ("city", models.CharField(max_length=50, verbose_name="شهر")),
                ("address", models.TextField(verbose_name="نشانی کامل")),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="کد پستی باید 10 رقم باشد", regex="^\\d{10}$"
                            )
                        ],
                        verbose_name="کد پستی",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="عرض جغرافیایی",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="طول جغرافیایی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="clinics/logos/",
                        verbose_name="لوگو",
                    ),
                ),
                (
                    "license_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره مجوز"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "allows_online_booking",
                    models.BooleanField(default=True, verbose_name="امکان رزرو آنلاین"),
                ),
                (
                    "requires_payment",
                    models.BooleanField(default=False, verbose_name="نیاز به پرداخت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "مرکز پزشکی",
                "verbose_name_plural": "مراکز پزشکی",
                "db_table": "clinics_clinic",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ClinicImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="clinics/images/", verbose_name="تصویر"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="تصویر اصلی"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر مرکز",
                "verbose_name_plural": "تصاویر مراکز",
                "db_table": "clinics_clinic_image",
                "ordering": ["order", "-is_primary"],
            },
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["city"], name="clinics_cli_city_d5aa71_idx"),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["province"], name="clinics_cli_provinc_e1b06a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["is_active"], name="clinics_cli_is_acti_979596_idx"
            ),
        ),
    ]
