# Generated by Django 4.2.28 on 2026-02-04 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinic",
            name="clinic_type",
            field=models.CharField(
                choices=[
                    ("office", "مطب شخصی"),
                    ("clinic", "کلینیک"),
                    ("hospital", "بیمارستان"),
                    ("center", "مرکز درمانی"),
                    ("laboratory", "آزمایشگاه"),
                    ("imaging", "مرکز تصویربرداری"),
                ],
                default="office",
                max_length=20,
                verbose_name="نوع مرکز",
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="عمومی (قابل مشاهده برای همه)"
            ),
        ),
        migrations.AddField(
            model_name="clinic",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_clinics",
                to=settings.AUTH_USER_MODEL,
                verbose_name="مالک/ایجاد کننده",
            ),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(
                fields=["clinic_type"], name="clinics_cli_clinic__58067f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clinic",
            index=models.Index(fields=["owner"], name="clinics_cli_owner_i_682062_idx"),
        ),
    ]
