# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "zarinpal_merchant_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Merchant ID زرین\u200cپال",
                    ),
                ),
                (
                    "zarinpal_sandbox",
                    models.BooleanField(
                        default=True, verbose_name="حالت تست زرین\u200cپال"
                    ),
                ),
                (
                    "zarinpal_active",
                    models.BooleanField(
                        default=False, verbose_name="زرین\u200cپال فعال"
                    ),
                ),
                (
                    "drik_api_key",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="API Key دریک",
                    ),
                ),
                (
                    "drik_sandbox",
                    models.BooleanField(default=True, verbose_name="حالت تست دریک"),
                ),
                (
                    "drik_active",
                    models.BooleanField(default=False, verbose_name="دریک فعال"),
                ),
                (
                    "default_gateway",
                    models.CharField(
                        choices=[("zarinpal", "زرین\u200cپال"), ("drik", "دریک")],
                        default="zarinpal",
                        max_length=20,
                        verbose_name="درگاه پیش\u200cفرض",
                    ),
                ),
                (
                    "min_payment_amount",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="حداقل مبلغ پرداخت"
                    ),
                ),
                (
                    "allow_deposit",
                    models.BooleanField(
                        default=True, verbose_name="امکان پرداخت بیعانه"
                    ),
                ),
                (
                    "allow_cash",
                    models.BooleanField(default=True, verbose_name="امکان پرداخت نقدی"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پرداخت",
                "verbose_name_plural": "تنظیمات پرداخت",
                "db_table": "payments_setting",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="شناسه یکتا",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ (تومان)"
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        choices=[
                            ("zarinpal", "زرین\u200cپال"),
                            ("drik", "دریک"),
                            ("cash", "نقدی"),
                            ("card", "کارت\u200cخوان"),
                        ],
                        max_length=20,
                        verbose_name="درگاه",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("full_payment", "پرداخت کامل"),
                            ("deposit", "بیعانه"),
                            ("remaining", "مابقی"),
                            ("refund", "بازپرداخت"),
                        ],
                        default="full_payment",
                        max_length=20,
                        verbose_name="نوع تراکنش",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Authority"
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شماره پیگیری",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره کارت"
                    ),
                ),
                (
                    "card_hash",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="هش کارت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("processing", "در حال پردازش"),
                            ("paid", "پرداخت شده"),
                            ("verified", "تأیید شده"),
                            ("failed", "ناموفق"),
                            ("cancelled", "لغو شده"),
                            ("refunded", "بازپرداخت شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="کد خطا"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="پیام خطا"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آدرس IP"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, null=True, verbose_name="User Agent"),
                ),
                (
                    "callback_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="داده\u200cهای Callback"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پرداخت"
                    ),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تأیید"
                    ),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="appointments.appointment",
                        verbose_name="نوبت",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش",
                "verbose_name_plural": "تراکنش\u200cها",
                "db_table": "payments_transaction",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="مبلغ بازپرداخت"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("cancelled", "لغو نوبت"),
                            ("duplicate", "پرداخت تکراری"),
                            ("error", "خطای سیستم"),
                            ("customer_request", "درخواست مشتری"),
                            ("other", "سایر"),
                        ],
                        default="cancelled",
                        max_length=20,
                        verbose_name="دلیل",
                    ),
                ),
                (
                    "reason_detail",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار"),
                            ("processing", "در حال پردازش"),
                            ("completed", "انجام شده"),
                            ("failed", "ناموفق"),
                            ("rejected", "رد شده"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شماره پیگیری بازپرداخت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ درخواست"
                    ),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ پردازش"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="پردازش توسط",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payments.transaction",
                        verbose_name="تراکنش اصلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "بازپرداخت",
                "verbose_name_plural": "بازپرداخت\u200cها",
                "db_table": "payments_refund",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["authority"], name="payments_tr_authori_8fddcf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(fields=["ref_id"], name="payments_tr_ref_id_3a4aa4_idx"),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["status", "created_at"], name="payments_tr_status_e3597b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["user", "created_at"], name="payments_tr_user_id_4ab1c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=["appointment"], name="payments_tr_appoint_75275b_idx"
            ),
        ),
    ]
