# Generated by Django 4.2.28 on 2026-02-04 09:23

import apps.patients.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("content", models.TextField(verbose_name="محتوا")),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="مهم"),
                ),
                (
                    "is_private",
                    models.BooleanField(default=False, verbose_name="خصوصی"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_patient_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد توسط",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_notes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "یادداشت بیمار",
                "verbose_name_plural": "یادداشت\u200cهای بیماران",
                "db_table": "patients_patient_note",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chief_complaint",
                    models.TextField(blank=True, null=True, verbose_name="شکایت اصلی"),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        blank=True, null=True, verbose_name="شرح حال بیماری"
                    ),
                ),
                (
                    "physical_examination",
                    models.TextField(
                        blank=True, null=True, verbose_name="معاینه فیزیکی"
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, null=True, verbose_name="تشخیص"),
                ),
                (
                    "prescription",
                    models.TextField(
                        blank=True, null=True, verbose_name="نسخه / درمان"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت\u200cها"
                    ),
                ),
                (
                    "blood_pressure",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="فشار خون"
                    ),
                ),
                (
                    "pulse_rate",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ضربان قلب"
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="دما (سلسیوس)",
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="وزن (کیلوگرم)",
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="قد (سانتی\u200cمتر)",
                    ),
                ),
                (
                    "next_visit_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاریخ مراجعه بعدی"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت پیگیری"
                    ),
                ),
                ("visit_date", models.DateField(verbose_name="تاریخ ویزیت")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_records",
                        to="appointments.appointment",
                        verbose_name="نوبت مرتبط",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرونده پزشکی",
                "verbose_name_plural": "پرونده\u200cهای پزشکی",
                "db_table": "patients_medical_record",
                "ordering": ["-visit_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.patients.models.medical_file_upload_path,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "تصویر"),
                            ("pdf", "PDF"),
                            ("lab_result", "نتیجه آزمایش"),
                            ("xray", "رادیولوژی"),
                            ("scan", "سی\u200cتی اسکن/MRI"),
                            ("ecg", "نوار قلب"),
                            ("prescription", "نسخه"),
                            ("other", "سایر"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="نوع فایل",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="عنوان"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حجم (بایت)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="patients.medicalrecord",
                        verbose_name="پرونده",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آپلود توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل پزشکی",
                "verbose_name_plural": "فایل\u200cهای پزشکی",
                "db_table": "patients_medical_file",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allergen",
                    models.CharField(max_length=100, verbose_name="عامل حساسیت"),
                ),
                (
                    "reaction",
                    models.TextField(blank=True, null=True, verbose_name="واکنش"),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "خفیف"),
                            ("moderate", "متوسط"),
                            ("severe", "شدید"),
                        ],
                        default="moderate",
                        max_length=20,
                        verbose_name="شدت",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="یادداشت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ثبت"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "حساسیت",
                "verbose_name_plural": "حساسیت\u200cها",
                "db_table": "patients_allergy",
            },
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["patient", "created_at"], name="patients_me_patient_fe12ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["doctor", "created_at"], name="patients_me_doctor__49be1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicalrecord",
            index=models.Index(
                fields=["visit_date"], name="patients_me_visit_d_de8606_idx"
            ),
        ),
    ]
