# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0001_initial"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("daily", "روزانه"),
                            ("weekly", "هفتگی"),
                            ("monthly", "ماهانه"),
                            ("yearly", "سالانه"),
                        ],
                        max_length=20,
                        verbose_name="نوع دوره",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                (
                    "total_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="کل درآمد",
                    ),
                ),
                (
                    "total_refunds",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="کل بازپرداخت",
                    ),
                ),
                (
                    "net_income",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="درآمد خالص",
                    ),
                ),
                (
                    "transaction_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد تراکنش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "خلاصه مالی",
                "verbose_name_plural": "خلاصه\u200cهای مالی",
                "db_table": "reports_financial_summary",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExportedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("appointments", "نوبت\u200cها"),
                            ("financial", "مالی"),
                            ("patients", "بیماران"),
                            ("doctors", "پزشکان"),
                            ("custom", "سفارشی"),
                        ],
                        max_length=20,
                        verbose_name="نوع گزارش",
                    ),
                ),
                (
                    "file_format",
                    models.CharField(
                        choices=[("excel", "Excel"), ("pdf", "PDF"), ("csv", "CSV")],
                        max_length=10,
                        verbose_name="فرمت فایل",
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="reports/exports/", verbose_name="فایل"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="حجم فایل"),
                ),
                (
                    "filters_applied",
                    models.JSONField(
                        blank=True, null=True, verbose_name="فیلترهای اعمال شده"
                    ),
                ),
                (
                    "rows_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد سطرها"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ انقضا"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exported_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش خروجی",
                "verbose_name_plural": "گزارش\u200cهای خروجی",
                "db_table": "reports_exported_report",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MonthlyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="سال")),
                ("month", models.PositiveIntegerField(verbose_name="ماه")),
                (
                    "total_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل نوبت\u200cها"
                    ),
                ),
                (
                    "completed_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای انجام شده"
                    ),
                ),
                (
                    "cancelled_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای لغو شده"
                    ),
                ),
                (
                    "new_patients",
                    models.PositiveIntegerField(default=0, verbose_name="بیماران جدید"),
                ),
                (
                    "unique_patients",
                    models.PositiveIntegerField(default=0, verbose_name="بیماران یکتا"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="درآمد کل",
                    ),
                ),
                (
                    "online_revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=14,
                        verbose_name="درآمد آنلاین",
                    ),
                ),
                (
                    "average_daily_revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="میانگین درآمد روزانه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش ماهانه",
                "verbose_name_plural": "گزارش\u200cهای ماهانه",
                "db_table": "reports_monthly_report",
                "ordering": ["-year", "-month"],
                "unique_together": {("doctor", "clinic", "year", "month")},
            },
        ),
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "total_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="کل نوبت\u200cها"
                    ),
                ),
                (
                    "completed_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای انجام شده"
                    ),
                ),
                (
                    "cancelled_appointments",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نوبت\u200cهای لغو شده"
                    ),
                ),
                (
                    "no_show_appointments",
                    models.PositiveIntegerField(default=0, verbose_name="عدم حضور"),
                ),
                (
                    "new_patients",
                    models.PositiveIntegerField(default=0, verbose_name="بیماران جدید"),
                ),
                (
                    "total_revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="درآمد کل",
                    ),
                ),
                (
                    "online_revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="درآمد آنلاین",
                    ),
                ),
                (
                    "cash_revenue",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="درآمد نقدی",
                    ),
                ),
                (
                    "refunded_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مبلغ بازپرداخت",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_reports",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش روزانه",
                "verbose_name_plural": "گزارش\u200cهای روزانه",
                "db_table": "reports_daily_report",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date"], name="reports_dai_date_4dc5c1_idx"),
                    models.Index(
                        fields=["doctor", "date"], name="reports_dai_doctor__676209_idx"
                    ),
                    models.Index(
                        fields=["clinic", "date"], name="reports_dai_clinic__13fa71_idx"
                    ),
                ],
                "unique_together": {("doctor", "clinic", "date")},
            },
        ),
    ]
