# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="تخصص"),
                ),
                (
                    "medical_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="کد نظام پزشکی"
                    ),
                ),
                (
                    "bio",
                    models.TextField(blank=True, null=True, verbose_name="بیوگرافی"),
                ),
                (
                    "education",
                    models.TextField(blank=True, null=True, verbose_name="تحصیلات"),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="سال\u200cهای تجربه"
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors/profiles/",
                        verbose_name="تصویر پروفایل",
                    ),
                ),
                (
                    "visit_duration",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                        verbose_name="مدت ویزیت (دقیقه)",
                    ),
                ),
                (
                    "gap_between_visits",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(60),
                        ],
                        verbose_name="فاصله بین نوبت\u200cها (دقیقه)",
                    ),
                ),
                (
                    "max_daily_appointments",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="حداکثر نوبت روزانه",
                    ),
                ),
                (
                    "max_advance_days",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="حداکثر روزهای رزرو آینده",
                    ),
                ),
                (
                    "min_cancel_hours",
                    models.PositiveIntegerField(
                        default=24, verbose_name="حداقل ساعت لغو نوبت"
                    ),
                ),
                (
                    "visit_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="هزینه ویزیت (تومان)",
                    ),
                ),
                (
                    "deposit_percent",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد بیعانه",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "allows_online_booking",
                    models.BooleanField(default=True, verbose_name="امکان رزرو آنلاین"),
                ),
                (
                    "requires_payment",
                    models.BooleanField(default=False, verbose_name="نیاز به پرداخت"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "پزشک",
                "verbose_name_plural": "پزشکان",
                "db_table": "doctors_doctor",
                "ordering": ["user__last_name", "user__first_name"],
            },
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="نام تخصص"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="نام انگلیسی",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="آیکون (FontAwesome)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="ترتیب")),
            ],
            options={
                "verbose_name": "تخصص",
                "verbose_name_plural": "تخصص\u200cها",
                "db_table": "doctors_specialization",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="WorkSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "شنبه"),
                            (1, "یکشنبه"),
                            (2, "دوشنبه"),
                            (3, "سه\u200cشنبه"),
                            (4, "چهارشنبه"),
                            (5, "پنج\u200cشنبه"),
                            (6, "جمعه"),
                        ],
                        verbose_name="روز هفته",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="ساعت شروع")),
                ("end_time", models.TimeField(verbose_name="ساعت پایان")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="حداکثر نوبت (اختیاری)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "تقویم کاری",
                "verbose_name_plural": "تقویم کاری",
                "db_table": "doctors_work_schedule",
                "ordering": ["day_of_week", "start_time"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "day_of_week"],
                        name="doctors_wor_doctor__155120_idx",
                    ),
                    models.Index(
                        fields=["clinic", "day_of_week"],
                        name="doctors_wor_clinic__2bba3b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("holiday", "تعطیل"),
                            ("vacation", "مرخصی"),
                            ("emergency", "اضطراری"),
                            ("other", "سایر"),
                        ],
                        default="holiday",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="دلیل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_holidays",
                        to="clinics.clinic",
                        verbose_name="مرکز (خالی = همه مراکز)",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعطیلی پزشک",
                "verbose_name_plural": "تعطیلات پزشکان",
                "db_table": "doctors_doctor_holiday",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "date"], name="doctors_doc_doctor__2d8e73_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorClinic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="مرکز اصلی"),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره اتاق"
                    ),
                ),
                (
                    "custom_visit_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="هزینه ویزیت سفارشی",
                    ),
                ),
                (
                    "custom_visit_duration",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="مدت ویزیت سفارشی"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctors",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clinics",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارتباط پزشک-مرکز",
                "verbose_name_plural": "ارتباطات پزشک-مرکز",
                "db_table": "doctors_doctor_clinic",
                "indexes": [
                    models.Index(
                        fields=["doctor", "clinic"],
                        name="doctors_doc_doctor__f2a9f0_idx",
                    )
                ],
                "unique_together": {("doctor", "clinic")},
            },
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["medical_code"], name="doctors_doc_medical_1f88cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["specialization"], name="doctors_doc_special_037046_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_active"], name="doctors_doc_is_acti_3a5153_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctor",
            index=models.Index(
                fields=["is_featured"], name="doctors_doc_is_feat_41116e_idx"
            ),
        ),
    ]
