# Generated by Django 4.2.28 on 2026-02-04 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0001_initial"),
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workschedule",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="clinics.clinic",
                verbose_name="مرکز",
            ),
        ),
    ]
