# Generated by Django 4.2.28 on 2026-02-06 04:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("clinics", "0002_clinic_clinic_type_clinic_is_public_clinic_owner_and_more"),
        ("doctors", "0002_alter_workschedule_clinic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام خدمت")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="شناسه یکتا",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="آیکون (FontAwesome)"
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="خدمات پیش\u200cفرض توسط سیستم ایجاد شده و قابل حذف نیستند",
                        verbose_name="پیش\u200cفرض سیستم",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "نوع خدمت",
                "verbose_name_plural": "انواع خدمات",
                "db_table": "doctors_servicetype",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="doctors_ser_slug_33cb5d_idx"),
                    models.Index(
                        fields=["is_active"], name="doctors_ser_is_acti_81ce0c_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="doctors_ser_sort_or_6a815c_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="InsuranceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام بیمه")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=100,
                        unique=True,
                        verbose_name="شناسه یکتا",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات"
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="آیکون"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="بیمه\u200cهای پیش\u200cفرض توسط سیستم ایجاد شده و قابل حذف نیستند",
                        verbose_name="پیش\u200cفرض سیستم",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "sort_order",
                    models.IntegerField(default=0, verbose_name="ترتیب نمایش"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "نوع بیمه",
                "verbose_name_plural": "انواع بیمه",
                "db_table": "doctors_insurancetype",
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(fields=["slug"], name="doctors_ins_slug_e80191_idx"),
                    models.Index(
                        fields=["is_active"], name="doctors_ins_is_acti_c30959_idx"
                    ),
                    models.Index(
                        fields=["sort_order"], name="doctors_ins_sort_or_9f789f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DoctorTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="مبلغ تعرفه (ریال)",
                    ),
                ),
                (
                    "deposit_required",
                    models.BooleanField(default=False, verbose_name="نیاز به بیعانه"),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="اگر صفر باشد از درصد بیعانه استفاده می\u200cشود",
                        max_digits=12,
                        verbose_name="مبلغ بیعانه (ریال)",
                    ),
                ),
                (
                    "deposit_percent",
                    models.IntegerField(
                        default=0,
                        help_text="اگر مبلغ بیعانه صفر باشد، از این درصد استفاده می\u200cشود",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد بیعانه",
                    ),
                ),
                (
                    "online_payment_required",
                    models.BooleanField(
                        default=False, verbose_name="الزام پرداخت آنلاین"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="توضیحات تعرفه"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        help_text="خالی = تعرفه عمومی برای همه مراکز",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tariffs",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
                (
                    "insurance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tariffs",
                        to="doctors.insurancetype",
                        verbose_name="نوع بیمه",
                    ),
                ),
                (
                    "service_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="tariffs",
                        to="doctors.servicetype",
                        verbose_name="نوع خدمت",
                    ),
                ),
            ],
            options={
                "verbose_name": "تعرفه پزشک",
                "verbose_name_plural": "تعرفه\u200cهای پزشک",
                "db_table": "doctors_doctortariff",
                "ordering": ["service_type__sort_order", "insurance_type__sort_order"],
                "indexes": [
                    models.Index(
                        fields=["doctor", "clinic"],
                        name="doctors_doc_doctor__2ee33d_idx",
                    ),
                    models.Index(
                        fields=["doctor", "is_active"],
                        name="doctors_doc_doctor__f3a2c4_idx",
                    ),
                    models.Index(
                        fields=["service_type"], name="doctors_doc_service_32a4bb_idx"
                    ),
                    models.Index(
                        fields=["insurance_type"], name="doctors_doc_insuran_ac1d48_idx"
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="doctortariff",
            constraint=models.UniqueConstraint(
                fields=("doctor", "clinic", "service_type", "insurance_type"),
                name="unique_tariff",
            ),
        ),
    ]
