# Generated by Django 4.2.28 on 2026-02-06 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_default_tariff_data"),
        ("doctors", "0003_servicetype_insurancetype_doctortariff_and_more"),
    ]

    operations = []
