# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("doctors", "0001_initial"),
        ("clinics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ نوبت")),
                ("time", models.TimeField(verbose_name="ساعت نوبت")),
                (
                    "queue_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شماره صف"
                    ),
                ),
                (
                    "estimated_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="زمان تقریبی ویزیت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در انتظار تأیید"),
                            ("confirmed", "تأیید شده"),
                            ("arrived", "حاضر شده"),
                            ("in_progress", "در حال ویزیت"),
                            ("visited", "ویزیت شده"),
                            ("cancelled", "لغو شده"),
                            ("no_show", "عدم حضور"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "booking_source",
                    models.CharField(
                        choices=[
                            ("online", "رزرو آنلاین"),
                            ("phone", "رزرو تلفنی"),
                            ("onsite", "حضوری"),
                            ("secretary", "توسط منشی"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="منبع رزرو",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "پرداخت نشده"),
                            ("deposit", "بیعانه پرداخت شده"),
                            ("paid", "پرداخت کامل"),
                            ("refunded", "بازپرداخت شده"),
                        ],
                        default="unpaid",
                        max_length=20,
                        verbose_name="وضعیت پرداخت",
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("onsite", "پرداخت در مطب"),
                            ("online_full", "پرداخت آنلاین کامل"),
                            ("online_deposit", "پرداخت بیعانه آنلاین"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="نوع پرداخت",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="هزینه ویزیت",
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ بیعانه",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="مبلغ پرداخت شده",
                    ),
                ),
                (
                    "patient_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت بیمار"
                    ),
                ),
                (
                    "secretary_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت منشی"
                    ),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, null=True, verbose_name="یادداشت پزشک"
                    ),
                ),
                (
                    "arrived_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان حضور"
                    ),
                ),
                (
                    "visit_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان شروع ویزیت"
                    ),
                ),
                (
                    "visited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پایان ویزیت"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان لغو"
                    ),
                ),
                (
                    "cancel_reason",
                    models.TextField(blank=True, null=True, verbose_name="دلیل لغو"),
                ),
                (
                    "reminder_sent",
                    models.BooleanField(
                        default=False, verbose_name="یادآوری ارسال شده"
                    ),
                ),
                (
                    "confirm_sms_sent",
                    models.BooleanField(
                        default=False, verbose_name="پیامک تأیید ارسال شده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="لغو شده توسط",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ایجاد شده توسط",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="بیمار",
                    ),
                ),
            ],
            options={
                "verbose_name": "نوبت",
                "verbose_name_plural": "نوبت\u200cها",
                "db_table": "appointments_appointment",
                "ordering": ["-date", "time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(max_length=50, verbose_name="فیلد تغییر یافته"),
                ),
                (
                    "old_value",
                    models.TextField(blank=True, null=True, verbose_name="مقدار قبلی"),
                ),
                (
                    "new_value",
                    models.TextField(blank=True, null=True, verbose_name="مقدار جدید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="appointments.appointment",
                        verbose_name="نوبت",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="تغییر توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه نوبت",
                "verbose_name_plural": "تاریخچه نوبت\u200cها",
                "db_table": "appointments_appointment_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="تاریخ")),
                ("time", models.TimeField(verbose_name="ساعت")),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="موجود"),
                ),
                (
                    "is_blocked",
                    models.BooleanField(default=False, verbose_name="مسدود شده"),
                ),
                (
                    "block_reason",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="دلیل مسدودیت",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="clinics.clinic",
                        verbose_name="مرکز",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="doctors.doctor",
                        verbose_name="پزشک",
                    ),
                ),
            ],
            options={
                "verbose_name": "تایم",
                "verbose_name_plural": "تایم\u200cها",
                "db_table": "appointments_time_slot",
                "ordering": ["date", "time"],
                "unique_together": {("doctor", "clinic", "date", "time")},
            },
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "date"], name="appointment_doctor__e7d63f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "date"], name="appointment_patient_83aa7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["clinic", "date"], name="appointment_clinic__f6186d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(fields=["status"], name="appointment_status_8fe9d7_idx"),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["payment_status"], name="appointment_payment_79f9ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["date", "queue_number"], name="appointment_date_fc3883_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="appointment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "cancelled"), _negated=True),
                fields=("doctor", "date", "time"),
                name="unique_appointment_slot",
            ),
        ),
    ]
