# Generated by Django 4.2.28 on 2026-02-06 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0003_servicetype_insurancetype_doctortariff_and_more"),
        ("clinics", "0002_clinic_clinic_type_clinic_is_public_clinic_owner_and_more"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="insurance_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="doctors.insurancetype",
                verbose_name="نوع بیمه",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="doctors.servicetype",
                verbose_name="نوع خدمت",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="tariff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="doctors.doctortariff",
                verbose_name="تعرفه اعمال\u200cشده",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="tariff_fee",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                help_text="Snapshot مبلغ تعرفه در لحظه رزرو - تغییرات بعدی تعرفه تأثیری روی نوبت ندارد",
                max_digits=12,
                verbose_name="مبلغ تعرفه در زمان رزرو (ریال)",
            ),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="clinic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="clinics.clinic",
                verbose_name="مرکز",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["service_type"], name="appointment_service_41a085_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["insurance_type"], name="appointment_insuran_5a3a69_idx"
            ),
        ),
    ]
