# Generated by Django 4.2.28 on 2026-02-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="API Key"
                    ),
                ),
                (
                    "line_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="شماره خط"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="فعال")),
                (
                    "send_appointment_confirm",
                    models.BooleanField(default=True, verbose_name="ارسال تأیید نوبت"),
                ),
                (
                    "send_appointment_reminder",
                    models.BooleanField(default=True, verbose_name="ارسال یادآوری"),
                ),
                (
                    "reminder_hours_before",
                    models.PositiveIntegerField(
                        default=24, verbose_name="ساعت قبل از یادآوری"
                    ),
                ),
                (
                    "send_queue_update",
                    models.BooleanField(
                        default=True, verbose_name="ارسال بروزرسانی صف"
                    ),
                ),
                (
                    "send_cancel_notification",
                    models.BooleanField(default=True, verbose_name="ارسال اعلان لغو"),
                ),
                (
                    "max_daily_sms",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="حداکثر پیامک روزانه"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "تنظیمات پیامک",
                "verbose_name_plural": "تنظیمات پیامک",
                "db_table": "notifications_sms_setting",
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="نام الگو"
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="عنوان")),
                (
                    "content",
                    models.TextField(
                        help_text="از متغیرها استفاده کنید: {patient_name}, {doctor_name}, {date}, {time}, {queue_number}, {clinic_name}",
                        verbose_name="محتوای پیامک",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "الگوی پیامک",
                "verbose_name_plural": "الگوهای پیامک",
                "db_table": "notifications_sms_template",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SMS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "receptor",
                    models.CharField(max_length=11, verbose_name="شماره گیرنده"),
                ),
                ("message", models.TextField(verbose_name="متن پیامک")),
                (
                    "template",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("appointment_confirm", "تأیید نوبت"),
                            ("appointment_reminder", "یادآوری نوبت"),
                            ("appointment_cancelled", "لغو نوبت"),
                            ("queue_update", "بروزرسانی صف"),
                            ("payment_success", "تأیید پرداخت"),
                            ("verification_code", "کد تأیید"),
                            ("welcome", "خوش\u200cآمدگویی"),
                            ("custom", "سفارشی"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="الگو",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "در صف ارسال"),
                            ("sent", "ارسال شده"),
                            ("delivered", "تحویل شده"),
                            ("failed", "ناموفق"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="شناسه پیامک",
                    ),
                ),
                (
                    "cost",
                    models.PositiveIntegerField(default=0, verbose_name="هزینه (ریال)"),
                ),
                (
                    "error_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="کد خطا"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="پیام خطا"),
                ),
                (
                    "related_model",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="مدل مرتبط"
                    ),
                ),
                (
                    "related_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="شناسه مرتبط"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ ارسال"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تحویل"
                    ),
                ),
            ],
            options={
                "verbose_name": "پیامک",
                "verbose_name_plural": "پیامک\u200cها",
                "db_table": "notifications_sms",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["receptor"], name="notificatio_recepto_c63844_idx"
                    ),
                    models.Index(
                        fields=["status"], name="notificatio_status_55f55b_idx"
                    ),
                    models.Index(
                        fields=["template"], name="notificatio_templat_c1f06a_idx"
                    ),
                    models.Index(
                        fields=["related_model", "related_id"],
                        name="notificatio_related_20d10b_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("message", models.TextField(verbose_name="پیام")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("info", "اطلاعات"),
                            ("success", "موفقیت"),
                            ("warning", "هشدار"),
                            ("danger", "خطر"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="لینک"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="خوانده شده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ خواندن"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "اعلان",
                "verbose_name_plural": "اعلان\u200cها",
                "db_table": "notifications_notification",
                "ordering": ["-created_at"],
            },
        ),
    ]
